In [99]:
import os
import pandas as pd

In [100]:
breed_weight_path = os.path.join("Resources","original","breed_weight.csv")

df_breed_weight = pd.read_csv(breed_weight_path) 
df_breed_weight

,Breed,Breed_clean,BreedID,Weight Male,Weight Female
0,Affenpinschers,Affenpinscher,1.0,7-10 pounds,7-10 pounds
1,Afghan Hounds,Afghan Hound,2.0,50-60 pounds,50-60 pounds
2,Airedale Terriers,Airedale Terrier,3.0,50-70 pounds,50-70 pounds
3,Akitas,Akita,5.0,100-130 pounds,70-100 pounds
4,Alaskan Malamutes,Alaskan Malamute,6.0,85 pounds,75 pounds
...,...,...,...,...,...
178,Icelandic Sheepdogs,Icelandic Sheepdog,NaN,30 pounds,25 pounds
179,Lagotti Romagnoli,Lagotti Romagnoli,NaN,28.5-35 pounds,24-31 pounds
180,Miniature American Shepherds,Miniature American Shepherd,NaN,20-40 pounds,20-40 pounds
181,Pyrenean Shepherds,Pyrenean Shepherd,NaN,15-30 pounds,15-30 pounds
182,Standard Schnauzers,Standard Schnauzer,NaN,35-50 pounds,30-45 pounds

In [101]:
#Drop original name
df_breed_weight= df_breed_weight.drop(columns=['Breed'])

In [102]:
#Rename column headers
df_breed_weight= df_breed_weight.rename(columns = {'Breed_clean' : 'breed_name', 'BreedID': 'breed_ID', 'Weight Male': 'weight_male', 'Weight Female': 'weight_female'})

In [103]:
#Drop N/As
df_breed_weight= df_breed_weight[df_breed_weight!=0].dropna()

In [115]:
#Reorder columns
df_breed_weight = df_breed_weight.reindex(columns= ['breed_ID', 'breed_name', 'weight_male','weight_female'])
df_breed_weight

,breed_ID,breed_name,weight_male,weight_female
0,1.0,Affenpinscher,7-10 pounds,7-10 pounds
1,2.0,Afghan Hound,50-60 pounds,50-60 pounds
2,3.0,Airedale Terrier,50-70 pounds,50-70 pounds
3,5.0,Akita,100-130 pounds,70-100 pounds
4,6.0,Alaskan Malamute,85 pounds,75 pounds
...,...,...,...,...
170,232.0,Wheaten Terrier,35-40 pounds,30-35 pounds
171,233.0,Whippet,25-40 pounds,25-40 pounds
172,236.0,Wire-haired Pointing Griffon,50-70 pounds,35 and 50 pounds
173,238.0,Xoloitzcuintle/Mexican Hairless,"10-15 pounds (toy), 15-30 pounds (miniature), ...","10-15 pounds (toy), 15-30 pounds (miniature), ..."
174,240.0,Yorkshire Terrier Yorkie,7 pounds,7 pounds

In [118]:
#Output pandas dataframe into CSV file and store it in 'clean' folder under Resources folder
output_path = os.path.join("Resources","clean","df_breed_weight_clean.csv")
print(output_path)
df_breed_weight.to_csv(output_path)

Resources\clean\df_breed_weight_clean.csv